vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:  '%document_directory%'
            upload_destination: '%kernel.project_dir%/public%document_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false